title: Mr Cloud
author: Marc Picornell
email: marc@mr-cloud.io
description: A blog about the Cloud and the best practice around it
github_username: marcpicornell

markdown: kramdown
#theme: jekyll-theme-cayman
remote_theme: chrisrhymes/bulma-clean-theme
